baseURL = "https://mentor.flatland.church/"
languageCode = "en-us"
title = "Mentorship at Flatland Church"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
